min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_alphanumeric_characters = 3
may_end_with_colon = false
quote_start_with_alphanumeric = true
needs_punctuation_end = true
needs_alphanumeric_start = true
needs_uppercase_start = true
disallowed_symbols = ['"', '<', '>', '+', '*', '\\', '#', '@', '^', '[', ']', '(', ')', '/', '\n', '«', '»',]
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;", ", ',", " :"]
abbreviation_patterns = [r"[[:upper:]]+\.*[[:upper:]]", r"(^|[[:space:]])[[:upper:]]\."]
